# Generated by Django 5.0.6 on 2024-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0002_produits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produits',
            options={},
        ),
        migrations.AlterModelManagers(
            name='produits',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='produits',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='email',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='password',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='username',
        ),
        migrations.AlterField(
            model_name='produits',
            name='Nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produits',
            name='Quantité',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.IntegerField(null=True),
        ),
    ]
