# Generated by Django 5.0.6 on 2024-08-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0003_alter_produits_options_alter_produits_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='Quantité',
        ),
    ]
