# Generated by Django 5.0.6 on 2024-09-01 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0004_remove_produits_quantité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='type',
            field=models.CharField(choices=[('salé', 'Salé'), ('gateaux', 'Gateaux'), ('tartes', 'Tartes'), ('venoiserie', 'Venoiserie'), ('confisserie', 'Confisserie'), ('snack', 'Snack'), ('glaces', 'Glaces'), ('gateau_trad', 'Gateau_trad')], max_length=50),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode_paiement', models.CharField(choices=[('en ligne', 'En Ligne'), ('especes', 'Especes')], max_length=50)),
                ('payé', models.BooleanField(default=0)),
                ('prix', models.IntegerField(null=True)),
                ('libellé', models.TextField(max_length=255, null=True)),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='len.produits')),
            ],
        ),
    ]
