# Generated by Django 5.0.6 on 2024-09-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0005_alter_produits_type_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Quantité',
            field=models.IntegerField(null=True),
        ),
    ]
