# Generated by Django 5.0.6 on 2024-09-01 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0006_commande_quantité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
