# Generated by Django 5.0.6 on 2024-09-01 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0008_alter_commande_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande_Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(null=True)),
                ('Quantité', models.IntegerField(null=True)),
                ('libellé', models.TextField(max_length=255, null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='len.produits')),
            ],
        ),
    ]
