# Generated by Django 5.0.6 on 2024-09-01 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0009_commande_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_de_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
