# Generated by Django 5.0.6 on 2024-09-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0010_commande_date_de_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livré',
            field=models.BooleanField(default=0),
        ),
    ]
