# Generated by Django 5.0.6 on 2024-09-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0011_commande_livré'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/')),
            ],
        ),
    ]
